apiVersion: v1
kind: Template
metadata:
  name: telecom-cloud-eapi
  labels:
    app: telecom-cloud-eapi
    template: telecom-cloud-eapi
    createdBy: Yassir

objects:
  
- apiVersion: v1
  kind: Service
  metadata:
    name: eapi-service
    labels:
      app: eapi-service
    annotations:
      openshift.io/generated-by: Yassir
  spec:
    ports:
    - name: 80-tcp
      protocol: TCP
      port: 80
      targetPort: 8090
    selector:
      app: eapi
      deploymentconfig: eapi
    type: ClusterIP
    sessionAffinity: None
  status:
    loadBalancer:
    
    
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: eapi
    labels:
      app: eapi
  spec:
    replicas: 1
    selector:
      app: eapi
      deploymentconfig: eapi
    template:
      metadata:
        labels:
          app: eapi
          deploymentconfig: eapi
      spec:
        containers:
          - env:
            - name: SAP_SERVER
              value: sap-service.myproject.svc
            - name: EAPI2_SERVER
              value: eapi2-service.myproject.svc  
            image: >-
              mtr.external.otc.telekomcloud.com/yassir/e-api:latest
            name: eapi
            ports:
              - containerPort: 8090
                protocol: TCP
            resources: {}
            imagePullPolicy: Always
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
        imagePullSecrets:
          - name: mtrtoken-yassir-secret
        securityContext: {}
    test: false
    triggers:
      - type: ConfigChange
    

