apiVersion: v1
kind: Template
metadata:
  name: telecom-cloud-webapp
  labels:
    app: telecom-cloud-webapp
    template: telecom-cloud-webapp
    createdBy: Yassir

objects:
 
# We will not use Routes. Instead Envoy Proxy is used. 
- apiVersion: v1
  kind: Route
  metadata:
    name: webapp-route
    labels:
      app: webapp-route
  spec:
    to:
      kind: Service
      name: webapp-service
    port:
      targetPort: 8092
  status: {}

 
- apiVersion: v1
  kind: Service
  metadata:
    name: webapp-service
    labels:
      app: webapp-service
    annotations:
      openshift.io/generated-by: Yassir
  spec:
    ports:
    - name: 80-tcp
      protocol: TCP
      port: 80
      targetPort: 8092
    selector:
      app: webapp
      deploymentconfig: webapp
    type: ClusterIP
    sessionAffinity: None
  status:
    loadBalancer:
     
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: webapp
    labels:
      app: webapp
  spec:
    replicas: 1
    selector:
      app: webapp
      deploymentconfig: webapp
    template:
      metadata:
        labels:
          app: webapp
          deploymentconfig: webapp
      spec:
        containers:
          - env:
            - name: BFF_SERVER
              value: bff-service.myproject.svc
            image: >-
              mtr.external.otc.telekomcloud.com/yassir/webapp:latest
            name: webapp
            ports:
              - containerPort: 8092
                protocol: TCP
            resources: {}
            imagePullPolicy: Always
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
        imagePullSecrets:
          - name: mtrtoken-yassir-secret
        securityContext: {}
    test: false
    triggers:
      - type: ConfigChange
    

